# About me
Hey there! 👋 I’m Thanh Nguyen, a 3rd year CS student interested in software and full-stack development. I'm a fan of basketball, football, and also pretty decent at playing table tennis and american pool.

## 1.1 Contact
- 📧 School Email: u7594144@anu.edu.au

- 📧 Personal Email: lethanh300504@gmail.com

## 1.2 What I Do
- **Frontend development**: Develop frontend and ui design using Next.js, React, Tailwind CSS, UI libraries (Shadcn, Aceternitiy, MaterialUI, MagicUI, and many more...)

- **Backend Development**: Experience in leveraging Spring Boot (Java) and Flask (Python) for RESTful APIs, tRPC (TypeScript) for RPCs 

- **Databases**: PostgreSQL, Neon, Supabase, Prisma, Liquibase for databases design

- **Developer tools**: Git, Github, Vercel, Google Cloud

## 1.3 Experience
**SWE Intern - Lyra  (Feb 2025 - Present)**
- Develop Full-stack webapps, Chrome Extensions using Next.js, tRPC, TypeScript, Prisma ORM

**SWE Intern - FPT Software (Nov 2024 - Jan 2025)**
- Utilized Spring Boot to develop RESTful APIs, with robust authentication and authorization using Spring Security and JWT Authentication
- Used PostgreSQL and Liquibase for databases migration.

**Undergrad Researcher - ANU (May 2024 - Sept 2024)**
- Web scraping using Scrapy and Python
- Constructed Data visualization tool using Matplotlib, Pandas, Numpy

**SWE Intern - Mobifone (Nov 2023 - Jan 2024)**
- Developed RESTful APIs using Spring Boot, Spring JDBC, MySQL

## 1.4 Education
🎓 Australian National University (ANU) (Feb 2023 – Expected Nov 2025)
- Bachelor of Information Technology
  
## 1.5 Fun Facts
I have a Poodle

